### ISSUE TITLE
Improve usability on filter component

### ISSUE THREAD

**Issue by annaiandresen** [dotkom/vengeful-vineyard#103]
- [x] Add a cancel button on "vis straffer i tidsrom"
- [x] Add a way to add punishment types under "filter by punishment type". Right now it is only possible to cancel a specific punishment, or add all punishments("Velg alle")
- [x] Possible bug in Finn bruker, this filtering option does not work for me

**Comment by VigdisIS** [comment]
Ref bug in Finn bruker - has this been fixed yet?:s

**Comment by annaiandresen** [comment]
noo dont think so o.o but its only on mac?
