### ISSUE TITLE
Users can create custom punishments

### ISSUE THREAD

**Issue by VigdisIS** [dotkom/vengeful-vineyard#16]
### Njål sa på genfors at man skal kunne legge til custom punishments så denne ble bumpa til MVP oof
---

Users should be able to create custom punishments, where they can customize both the name of the punishment and it's value. They should also be able to add a visualization of the punishment.

There should be a button allowing users to create and add new punishments which are restricted to the group they are adding it to. When the user presses the button, a menu should pop up where the user can choose a name for their new punishment, as well as the amount the punishment is worth and upload an icon to display the punishment. After it is added, only the users in the specific group it was added to will be able to see it and utilize it.

**Comment by jfremstad** [comment]
Maybe we only want Admins (in the group) to be able to create custom punishments?
