### ISSUE TITLE
Wall of shame within groups

### ISSUE THREAD

**Issue by annaiandresen** [dotkom/vengeful-vineyard#17]
**Is your feature request related to a problem? Please describe.**
As of now, there is a Wall of Shame of all members in Online linjeforening. First of all, there is no way to filter out active and inactive within the student organization. We believe that it is more important to only be able to view a wall of shame of people in your group to remove unnecessary information.

**Describe the solution you'd like**
Add a feature which allows each group to have their own 'Wall of Shame'. The Wall of Shame is group specific, and only visible for group members.

**Comment by jfremstad** [comment]
"A wall of shame" for a group will be getting all active and verified punishments and calculating the total of these.
