### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by jfremstad** [dotkom/vengeful-vineyard#27]
We can probably use Drone or something to run linters, formatting checks, compilers etc. to verify that our commits are good.

Steps:

- npx prettier -c frontend/src
- npx svelte-check --fail-on-warnings
- npm run build

**Comment by jfremstad** [comment]
Can extend the hooks used by the backend: https://github.com/dotkom/vengeful-vineyard/blob/master/.pre-commit-config.yaml

**Comment by annaiandresen** [comment]
- [ ] frontend CI
