### ISSUE TITLE
wall-of-shame only fetching top 30 when scrolling 

### ISSUE THREAD

**Issue by CzternastyHembre** [dotkom/vengeful-vineyard#330]
To Reproduce
**Steps to reproduce the behavior:**

1. Go to 'https://vinstraff.no/#/wall-of-shame'
2. Scroll down to the bottom
3. See that the same top 30 people is fetched.

**Comment by jotjern** [comment]
Ser på det!

**Comment by jotjern** [comment]
Fixed
