### ISSUE TITLE
Create or find a logo

### ISSUE THREAD

**Issue by jfremstad** [dotkom/vengeful-vineyard#34]

**Comment by nyd3lig** [comment]
I would like to tackle this, is there any specific type of logo it should be?

**Comment by jfremstad** [comment]
I don't know much about designing logos, but I think what we're looking for is:

- Size: 250px x 100px
- Vector graphics is great
- Should contain the name (Vengeful vineyard)
- Since the system will be used for giving (primarily) wine-punishments it could be a good idea to incorporate that somehow
- The color surrounding the logo will be #0d5474

**Comment by dzienisz** [comment]
What do you like from this search? https://www.google.com/search?q=angry+grapes&tbm=isch&ved=2ahUKEwjHzr-1pLzsAhUDsioKHeGwDasQ2-cCegQIABAA&oq=angry+grapes&gs_lcp=CgNpbWcQAzIECAAQEzoICAAQBxAeEBM6BggAEAcQHlDKF1iRHGDQHWgAcAB4AIABcogBhgSSAQM0LjKYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=ojuLX8f1DIPkqgHh4bbYCg&bih=971&biw=1680

**Comment by annaiandresen** [comment]
Something like the first three images could work!
