### ISSUE TITLE
Wall of shame straffer vises dobbelt

### ISSUE THREAD

**Issue by CzternastyHembre** [dotkom/vengeful-vineyard#348]
tenker bilder beskriver problemet bra her (dette er kun ett av mange eksempler) (Carolina har godtatt å vise bilder herifra):

Bilde fra backlog sin redwine (den fungerer som den skal)

![image](https://uploads.linear.app/f2f2782a-dee3-414e-b6f1-cda51c6aa30b/88342df5-bee7-42a2-874f-7eb9f5b5a370/8c51e787-1e39-4880-8248-42e4ff4f39d0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2YyZjI3ODJhLWRlZTMtNDE0ZS1iNmYxLWNkYTUxYzZhYTMwYi84ODM0MmRmNS1iZWU3LTQyYTItODc0Zi03ZWI5ZjViNWEzNzAvOGM1MWU3ODctMWUzOS00ODgwLTgyNDgtNDJlNGZmNGYzOWQwIiwiaWF0IjoxNzExMDIxMjQxLCJleHAiOjMzMjgxNTgxMjQxfQ.jM6Kv0Pks8v4GJeSA1k8VBE_R3vVSxuo5ay_19ip2Cs "=998x")

Bilde fra wall of shame av caro sine nyligste straffer:

![image](https://uploads.linear.app/f2f2782a-dee3-414e-b6f1-cda51c6aa30b/66162897-ef7c-4d67-bb6a-f3ce0c505e21/ebd149b4-af64-48e3-95ed-a986e3cb9cec?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2YyZjI3ODJhLWRlZTMtNDE0ZS1iNmYxLWNkYTUxYzZhYTMwYi82NjE2Mjg5Ny1lZjdjLTRkNjctYmI2YS1mM2NlMGM1MDVlMjEvZWJkMTQ5YjQtYWY2NC00OGUzLTk1ZWQtYTk4NmUzY2I5Y2VjIiwiaWF0IjoxNzExMDIxMjQxLCJleHAiOjMzMjgxNTgxMjQxfQ.lhvcDiiof0HKQqntHJOtpNQJ7XBisnbW3M5x_eDtAbg "=1026x")

**Comment by jotjern** [comment]
Skal være i orden nå :-) ty til @Terbau
